---
- name: Manage nsg's with azure collection - associate security group to subnet
  hosts: localhost
  tasks:

    # Create new subnet2 and associate security group azureVMs-new-nsg with subnet2
    - azure.azcollection.azure_rm_subnet:
        resource_group: azureVMs-rg
        virtual_network_name: azureVMs-vnet
        name: subnet2
        address_prefix_cidr: "10.0.3.0/24"
        security_group: azureVMs-new-nsg
