---
- name: Manage nsg's with azure collection - edit security group
  hosts: localhost
  tasks:

    # Edit security group - outfield_1-new-nsg
    - azure.azcollection.azure_rm_securitygroup:
        resource_group: outfield-rg
        name: outfield-new-nsg
        rules:
          - name: Allow-SSH-from-Home
            protocol: Tcp
            source_address_prefix: '173.122.148.0/24'
            destination_port_range: 22-24
            access: Allow
            priority: 100
            direction: Inbound

          - name: ICMP
            protocol: Icmp
            priority: 203
       
        tags:
          testing: testing
          delete: on-exit
