---
- name: Manage nsg's with azure collection - create security group
  hosts: localhost
  tasks:
    
    # Create security group - outfield_1-new-nsg
    - azure.azcollection.azure_rm_securitygroup:
        resource_group: outfield-rg
        name: outfield-new-nsg
        purge_rules: yes
        rules:
          - name: Deny-SSH
            protocol: Tcp
            destination_port_range: 22
            access: Deny
            priority: 200
            direction: Inbound

          - name: 'Allow-SSH-from-specifc-sources_addresses'
            protocol: Tcp
            source_address_prefix:
              - '174.109.158.0/24'
              - '174.109.159.0/24'
            destination_port_range: 22
            access: Allow
            priority: 201
            direction: Inbound

          - name: 'Allow-80-and-443-from-specifc-sources_addresses'
            protocol: Tcp
            source_address_prefix:
              - '174.109.158.0/24'
              - '174.109.159.0/24'
            destination_port_range:
              - 80
              - 443
            access: Allow
            priority: 202
